name: Publish release APK

on:
  push:

jobs:
  build-release-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 19
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
      - name: Build release APK
        run: ./gradlew assembleLawnWithQuickstepRelease
      - name: Publish artifact
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/outputs/apk/lawnWithQuickstep/release/*.apk
          token: ${{ secrets.GITHUB_TOKEN }}
