name: Publish release APK

on:
  push:

jobs:
  build-release-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 19
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
          cache-read-only: false
      - name: Build release APK
        run: ./gradlew assembleLawnWithQuickstepRelease
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
      - name: Publish artifact
        uses: ncipollo/release-action@v1
        with:
          tag: $NOW
          artifacts: build/outputs/apk/lawnWithQuickstep/release/*.apk
          token: ${{ secrets.GITHUB_TOKEN }}
