name: CI

on:
  push:
    branches:
      - trunk
    paths-ignore:
      - '.idea/**'
      - '.gitattributes'
      - '.github/**.json'
      - '.gitignore'
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'
  pull_request:
    branches:
      - trunk
    paths-ignore:
      - '.idea/**'
      - '.gitattributes'
      - '.github/**.json'
      - '.gitignore'
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - uses: gradle/gradle-build-action@v3-prerelease
        with:
          dependency-graph: ${{ github.ref == 'refs/heads/release' && 'generate-and-submit' || 'disabled'}}
          gradle-home-cache-cleanup: true
          cache-encryption-key: Da25KUVSE5jbGds2zXmfXw==
      - run: ./gradlew assembleLawnWithQuickstepRelease
      - uses: actions/upload-artifact@v3
        if: github.ref == 'refs/heads/trunk' && github.event_name == 'push'
        with:
          name: Release APK
          path: |
            build/outputs/apk/lawnWithQuickstep/release/*.apk
            build/outputs/mapping/lawnWithQuickstepRelease/mapping.txt


  check-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - uses: gradle/gradle-build-action@v3-prerelease
        with:
          gradle-home-cache-cleanup: true
      - run: ./gradlew spotlessCheck
